[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
offset.x = 0 # For letter spacing (default: 0)
offset.y = 0 # For line spacing (default: 0)

[font.normal]
# family = "CodeNewRoman Nerd Font Mono"
family = "Maple Mono NF"
# family = "MonacoLigaturized Nerd Font Mono"
# family = "RecMonoLinear Nerd Font Mono"
# family = "RecMonoCasual Nerd Font Mono"
style = "SemiBold"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',â”‚`|:"' ()[]{}<>'''

[window.dimensions]
columns = 80
lines = 25

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true

import = [
  "/home/tjagad/.config/alacritty/size.toml",
  "/home/tjagad/.config/alacritty/catppuccin-mocha.toml",
]
